### ISSUE TITLE
请问下，成员函数有const修饰，如何来mock

### ISSUE THREAD

**Issue by hai008** [ez8-co/emock#14]

**Comment by orca-zhang** [comment]
抱歉，很久没有用c++了，常成员函数我理解和普通成员函数在函数signature上，除了windows下有区别，linux下应该是一样的，有尝试过用普通全局函数mock嘛，感谢

**Comment by orca-zhang** [comment]
用全局函数的话，把第一个参数定义为const Object*类型尝试，常成员函数的本质是传递了一个常对象给成员函数，所以对象的成员无法被修改

**Comment by orca-zhang** [comment]
你好，b7f60efbb06de9d4c0c8a01814d817d7b72f5200 14707f43606491b6d05ca8d6ee53bbe225b95c9d 这两个提交增加了常成员函数的支持
