### ISSUE TITLE
如何把EMOCK之后的函数设置为不被MOCK的状态

### ISSUE THREAD

**Issue by caimagic** [ez8-co/emock#16]
我想在多个TEST中 mock同一个函数，但是mock的返回值结果是不一样的，例如如下代码，TEST-01设置fun返回值为1，TEST-02设置fun返回值为2. 我的运行结果是TEST-01是成功的，但是TEST-02是失败的。怎么样才能是TEST-02也成功吗？
```

int fun()
{
  return 0;
}

// Success
TEST(Demo, 01)
{
  EMOCK(fun)
    .expects(atLeast(1))
    .will(returnValue(1));

  EXPECT_EQ(1, fun());

}

// Fail, because 'fun' return value is 1. 
TEST(Demo, 02)
{
  EMOCK(fun)
    .expects(atLeast(1))
    .will(returnValue(2));
  
  EXPECT_EQ(2, fun());
}
```

**Comment by orca-zhang** [comment]
我发现确实文档里面没有写，这块我有空得补全了

可以使用
`GlobalMockObject::verify();`
verify，这里会自动执行reset，需要验证所有的mock是否符合期望

如果单单只想reset，也可以：
`GlobalMockObject::reset();`
