### ISSUE TITLE
请问常函数可以mock吗？

### ISSUE THREAD

**Issue by winter2022inhc** [ez8-co/emock#19]
请问常函数可以mock吗？我mock常函数总是报语法不对。另外在wiki中的使用手册是不是看不到了？多谢回复。

**Comment by orca-zhang** [comment]
看上去和 #14 有点像，wiki之前一直没有补全，可以暂时百度mockcpp的用法，约定的用法暂时没有改变的

**Comment by orca-zhang** [comment]
你好， https://github.com/ez8-co/emock/commit/b7f60efbb06de9d4c0c8a01814d817d7b72f5200 https://github.com/ez8-co/emock/commit/14707f43606491b6d05ca8d6ee53bbe225b95c9d 这两个提交增加了常成员函数的支持
