### ISSUE TITLE
你好，请问mock普通成员函数为什么会崩溃？

### ISSUE THREAD

**Issue by winter2022inhc** [ez8-co/emock#20]
1、我mock动态链接库dll中的普通函数总是会报异常。
emock语句可以正常执行。调用mock后的函数时报如下异常：
发生异常：W32/0xC0000005
Unhandled exception at 0x00007FF9B14677BB in XXX.exe: 0xC0000005: Access violation executing location 0x00007FF9B14677BB.
2、mock虚函数虽然没有异常，但是mock没有生效，还是走的mock前的函数流程。
请问这是什么原因呢？
感谢回复！

**Comment by orca-zhang** [comment]
最近 #26 #27 修复了数值类型问题，可以尝试一下。

**Comment by orca-zhang** [comment]
issue先关闭啦，如果还有问题可以reopen或者再开issue反馈哦，感谢反馈
