### ISSUE TITLE
经常不知原因的段错误

### ISSUE THREAD

**Issue by hai008** [ez8-co/emock#23]
_ZN5emock16getDemangledNameEPKc+0x1f)[0xa4b7df]
emock/src/SymbolRetriever.cpp:439(_findAddr<Elf64_Ehdr, Elf64_Shdr, Elf64_Sym>)[0xa4973f]
emock/src/SymbolRetriever.cpp:477(_ZN5emock14symbolRetrieveEPNS_12_GLOBAL__N_114ISymbolCheckorE.constprop.94)[0xa4a332]

**Comment by orca-zhang** [comment]
你好，最近在ubuntu场景下发现并修复了函数名称获取错误导致未获取到函数地址的类似问题，不知道有无覆盖你使用的操作系统。

**Comment by hai008** [comment]
后面再验证一下，用的是centos。
最近在用lmock了，这个没有问题，建议看下lmock，逻辑简单，并且稳定

**Comment by orca-zhang** [comment]
感谢反馈，看了一下确实简单很多。
