### ISSUE TITLE
mock 类成员函数 失败 （虚函数 和 普通成员函数 都失败 ）

### ISSUE THREAD

**Issue by Jackjiangtao** [ez8-co/emock#24]
使用 msvc ，但是 win32 平台是好的），使用demo为给定demo，x64平台有问题

**Comment by orca-zhang** [comment]
#26 #27 有两个朋友发现一个是数据范围过小的问题，一个是类型转换的问题，目前已修复，可以再确认一下，感谢反馈。

**Comment by orca-zhang** [comment]
issue先关闭啦，如果还有问题可以reopen或者再开issue反馈哦，感谢反馈
