### ISSUE TITLE
有计划发布一个release版本么

### ISSUE THREAD

**Issue by hellosk** [ez8-co/emock#25]
当前只有master分支，没有打tag，没有版本号，项目引入需要填版本号。
请问有计划发布一个release版本么？

**Comment by orca-zhang** [comment]
MacOS下还有点小问题，修复以后考虑打一个0.9

**Comment by orca-zhang** [comment]
打了一个版本，v0.9.0

**Comment by orca-zhang** [comment]
issue先关闭啦，如果还有问题可以reopen或者再开issue反馈哦，感谢反馈
