### ISSUE TITLE
mingw64无法编译通过

### ISSUE THREAD

**Issue by xinxijishuwyq** [ez8-co/emock#31]
emock-master\emock-master\src\Formatter.cpp:41:44: error: cast from 'void*' to 'long unsigned int' loses precision [-fpermissive]
    oss << reinterpret_cast<unsigned long>(p);

**Comment by orca-zhang** [comment]
#10

**Comment by orca-zhang** [comment]
我尝试修复了一下，再试试看还有其他错误不

**Comment by xinxijishuwyq** [comment]
> 我尝试修复了一下，再试试看还有其他错误不
出现新错误，环境mingw7.3
C:\Users\ken\Desktop\emock-master\emock-master\src\SymbolRetriever.cpp:33:11: fatal error: sys/mman.h: No such file or directory
  #include <sys/mman.h>
           ^~~~~~~~~~~~
compilation terminated.
mingw32-make.exe[2]: *** [src\CMakeFiles\emock.dir\build.make:931: src/CMakeFiles/emock.dir/SymbolRetriever.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:97: src/CMakeFiles/emock.dir/all] Error 2
mingw32-make.exe: *** [Makefile:135: all] Error 2

**Comment by orca-zhang** [comment]
我搭个MinGW环境看看

**Comment by xinxijishuwyq** [comment]
> 我搭个MinGW环境看看

多谢大佬

**Comment by orca-zhang** [comment]
改好了~试下，有问题可以reopen
