### ISSUE TITLE
Cannot build in windows

### ISSUE THREAD

**Issue by muhdhisham** [ez8-co/emock#39]
While generating makefile this error occurs in windows. I guess  sys/mman.h is not available for windows. Then how can I run emock in windows. Can anyone please tell the step by step procedure to get emock running? It would be helpful. 

emock-master\emock-master\src\SymbolRetriever.cpp:33:18: fatal error: sys/mman.h: No such file or directory
   33 |         #include <sys/mman.h>

**Comment by orca-zhang** [comment]
Which compiler or IDE are you using? Is it MinGW or cygwin under windows?

**Comment by muhdhisham** [comment]
I'm using MinGW. Can you please help?

**Comment by orca-zhang** [comment]
Just have a try.

**Comment by muhdhisham** [comment]
Emock/src/SymbolRetriever.cpp:21:22: fatal error: DbgHelp.h: No such file or directory
[build]   #include <DbgHelp.h>

/Emock/src/Trampoline.cpp:24:17: error: '_W64' does not name a type
[build]          typedef _W64 unsigned int uintptr_t;

Why is these errors showing? Cannot build. Build stops due to these errors

**Comment by muhdhisham** [comment]
Using mingw from mysys2 fixed the issue
