### ISSUE TITLE
emock/src/Trampoline.cpp line 135 logical error "unsigned long begin, end, last_end = 0;"

### ISSUE THREAD

**Issue by kiddy818** [ez8-co/emock#7]
emock/src/Trampoline.cpp :
line 135 "last_end = 0;"
line 153  "last_end = end;"
when do line 130 while, the line 153's effect will be covered by line 135.
so line 135 should before line 130.

like this:
unsigned long begin, end, last_end = 0;
while(!feof(fp)) {
...

**Comment by orca-zhang** [comment]
I'll fix it, thanks a lot for your very important cue.

**Comment by orca-zhang** [comment]
#d59b06f915b41cb80a1d3f66a0fb8d17e52b70b9 has fix it
Thanks.
