### ISSUE TITLE
mac os compile error

### ISSUE THREAD

**Issue by xiaolang315** [ez8-co/emock#9]
cmake info:
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xxx/code/emock/build
==============================================
compile info:
[  1%] Building CXX object src/CMakeFiles/emock.dir/SymbolRetriever.cpp.o
/Users/zhangchao/code/emock/src/SymbolRetriever.cpp:30:11: fatal error:
      'link.h' file not found
        #include <link.h>
                 ^~~~~~~~
1 error generated.

**Comment by orca-zhang** [comment]
Remove this line to check which function is related with `link.h`, then find out an alternative solution.

> #include <link.h>

**Comment by orca-zhang** [comment]
最新支持了MacOS，可以尝试一下。

**Comment by orca-zhang** [comment]
issue先关闭啦，如果还有问题可以reopen或者再开issue反馈哦，感谢反馈
